artifact_dir: artifact

data_ingestion:
  root_dir: artifact/data-ingestion
  url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  input_dir: artifact/data-ingestion/data.zip
  output_dir: artifact/data-ingestion/



data_validation:
  root_dir: artifact/data_validation
  unzip_data_dir: artifact\data-ingestion\winequality-red.csv
  STATUS_FILE: artifact/data_validation/status.txt


data_transformation:
  root_dir: artifact/data_transformation
  data_path: artifact/data-ingestion/winequality-red.csv

model_trainer:
  root_dir: artifact/model_trainer
  train_data_path: artifact/data_transformation/train.csv
  test_data_path: artifact/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifact/model_evaluation
  test_data_path: artifact/data_transformation/test.csv
  model_path: artifact/model_trainer/model.joblib
  metric_file_name: artifact/model_evaluation/metrics.json